name: Trigger website rebuild

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "veer-application-website-test"]
jobs:
  trigger:
    runs-on: ubuntu-22.04
    steps:
    - name: Trigger
      env:
        WEBSITE_TRIGGER_PAT: ${{ secrets.WEBSITE_TRIGGER_PAT }}
      run: |
        curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $WEBSITE_TRIGGER_PAT" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/chipsalliance/chips-alliance-website/actions/workflows/hugo.yml/dispatches -d'{"ref":"main"}'
